### ISSUE TITLE
Intégrer TVDebout/StreamDebout sur la homepage

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#104]
TV Debout retransmet en live tous les soirs depuis la Place de la République. 

Leurs flux sont dispos sur [YouTube](https://www.youtube.com/channel/UCRLZ1A3OweyAlESd89Ho7_A) et sur le site [http://tvdebout.zkp.fr/](http://tvdebout.zkp.fr/)

L'idée est d'intégrer leur lecteur directement sur la homepage, et de diffuser le live lorsqu'il est en train de streamer. 

Voir le code source du site pour la source du flux HLS, et intégrer un lecteur sur le site. 

Contacter @max-debout sur le chat.

**Comment by Neroth** [comment]
#130

**Comment by alexsegura** [comment]
En attendant que TVDebout remette son stream, on va essayer d'intégrer joliment les X derniers replays de [TvDebout](https://www.youtube.com/channel/UCRLZ1A3OweyAlESd89Ho7_A) et [StreamDebout](https://www.youtube.com/channel/UCeC5h9Kdszz2ay8efD6qECA) depuis YouTube. 

Apparemment, le widget YouTube ne permet pas de récupérer un liste de replays. 

Voir comment faire avec l'[API YouTube](https://developers.google.com/youtube/v3/docs/)

cc @mdamien

**Comment by alexsegura** [comment]
Voir #149

**Comment by alexsegura** [comment]
TVDebout a désormais sont propre site nuitdebout.fr/tvdebout, à priori on va déplacer les contenu là-dessus. 

Egalement vu avec Mehdi, la diffusion n'étant pas stable, on va voir pour mettre le live depuis YouTube (@Neroth va s'énerver 😄)
