### ISSUE TITLE
Utiliser wp-cli pour installer le projet

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#106]
Le projet [WP-Cli](http://wp-cli.org/) permet de manipuler Wordpress via la ligne de commande. 

Afin d'alléger le dépôt, il serait judicieux de refaire le provisionning de la machine de développement avec ça. 
- Installation de Wordpress
- Création de la base de données
- Installation des plugins

**Comment by Nhacsam** [comment]
Je regarde ce que je peux faire. Ça me parait cool. Je part sur un nouveau repo plutôt que de faire un `rm -rf`

**Comment by alexsegura** [comment]
L'idée c'était plutôt de continuer le développement ici 😄 

Faire un second dépôt avec seulement le thème est une bonne idée aussi, une fois stabilisé. 

Pas de souci pour supprimer les dossiers/fichiers de Wordpress Core dans ce dépôt, au contraire, du moment que les machines de développement continuent de fonctionner.

**Comment by Nhacsam** [comment]
Ça donne ça : https://github.com/nuitdebout/wordpress/pull/110
Comme promis, il ne reste plus grand chose. Ça utilise le thème dans le 2ieme Repo.

Je suis un peu déçu d'avoir du garder l'export en sql et de ne pas avoir pu en utiliser un en xml. Mais il manquait trop de chose :/

Il faut encore que je mette à jour le README

**Comment by alexsegura** [comment]
Du coup tu veux pas tester WP-Cli ? 😬 

Ca permettrait d'alléger le dépôt simplement, tout en gardant la structure. 
Et d'automatiser, l'installation des plugins en local c'est relou. 

Ya aussi du boulot pour exporter un jeu de données allégé depuis la production. 
WP-Cli permet d'exporter et d'importer apparemment : http://wp-cli.org/commands/.
Je ne connais pas les bonnes pratiques pour Wordpress...
J'ai importé #116 depuis le tableau. 

Donc on pourrait apprendre à s'en servir pour automatiser plein de trucs. 

Par contre ton truc avec Ansible pour la VM Vagrant (si j'ai bien compris ?) c'est cool, c'est plus propre que ce que j'ai fait 😓

**Comment by Nhacsam** [comment]
Oui je suis en train tkt
Je l'installe et l'utilise dans la vagrant au moment du provisionning.

Pour l'export, j'ai essayé, mais il manquait les configs pour les plugins, acf and Co. Du coup ça rendait tout moche.
Je referait des tests quand je serait arrivé à une base stable avec le sql

**Comment by Nhacsam** [comment]
Bon, ça marche pas trop mal, mis à part le dump sql qui n'est pas à jour :smile: https://github.com/nuitdebout/wordpress/pull/117

**Comment by alexsegura** [comment]
Bien joué Nicolas ! Maintenant on peut enchaîner sur les trucs moins geek 😄
