### ISSUE TITLE
Design des "taxonomies" (categories et tags)

### ISSUE THREAD

**Issue by tomplays** [nuitdebout/wordpress#111]
Maquetter l'affichage des "tags" et "catégories" d'un article (soit sous l'auteur, soit après le contenu par exemple)

**Comment by uneyouya** [comment]
![5_nuitdebout_article](https://cloud.githubusercontent.com/assets/19183873/15085296/29ffa38c-13e2-11e6-9071-2aee0d25e3f2.jpg)
