### ISSUE TITLE
Ne plus compiler le thème dans la VM

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#124]
Problème avec Node-Sass, il faut compiler le thème sur la machine de dev.

**Comment by Atala** [comment]
Je ne sais pas si c'est vraiment un problème, cela vient du fait que le binaire est différent pour OSX et Linux.

Ajouté à la doc [ici](https://github.com/nuitdebout/wordpress/pull/117/files/a0639a7ec17ca3cda766d5dae48efb7ac1989aa1..952fc9c6b8915e81caa229ee93cd7b9edddfae0e#diff-0730bb7c2e8f9ea2438b52e419dd86c9R83) mais supprimé par la suite (?).

**Comment by alexsegura** [comment]
Moi de ce que je vois c'est encore fait dans la VM, je vais creuser.
