### ISSUE TITLE
Déprécier acf_options_page (widget)

### ISSUE THREAD

**Issue by Nhacsam** [nuitdebout/wordpress#126]
Faire en sorte de plus avoir besoin de acf_options_pages

**Comment by alexsegura** [comment]
Fixé dans #190 

Pour avoir le même comportement (des options globales au site, ou du moins des options pour la homepage), lorsque le site est configuré pour afficher une page statique en page d'accueil, il est facile d'attacher des métadonnées à la page et de les récupérer. 
Mais ça ne présente pas bcp d'intérêt AMHA, les widgets/shortcodes sont plus souples. 

Par contre on peut utiliser cette technique pour avoir des pages d'accueil custom pour les multi-sites 😄
