### ISSUE TITLE
Importation des données

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#142]
@Atala @tomplays 

On peut discuter ici de ces scripts d'importation. 

J'ai mis les deux travaux dans la branche `import` 
https://github.com/nuitdebout/wordpress/commits/import

J'ai déplacé les scripts : 

```
theme/bin/import_wiki.php
theme/bin/import_doleances.php
```

On ne peut les lancer que depuis la ligne de commande, mais par contre c'est relou de charger Wordpress en ligne de commande. 
Heureusement WP-Cli permet de le faire avec [eval-file](https://wp-cli.org/commands/eval-file/), et il est installé dans la VM 😄 

```
vagrant ssh
cd /var/www/nuitdebout
wp eval-file wp-content/themes/nuitdebout/bin/import_doleances.php
```

J'ai juste commencé le script `import_wiki.php` je vais un peu continuer dessus

**Comment by Atala** [comment]
Ok To-Do de mon côté : 
- [x] check qu'on est bien en CLI
- [ ] ajouter l'ID du site en argument (-> regarder comment on fait pour ajouter des args)
  -> ce soir

Toujours un White Screen Of Death at `wp_insert_post` en local pour moi, si quelqu'un peut tester ou me dire comment récupérer plus de logs c'est avec plaisir.

**Comment by alexsegura** [comment]
Check qu'on est en cli je l'ai fait dans le script. 

> Toujours un White Screen Of Death at wp_insert_post en local pour moi

Tu as lancé avec `wp eval-file` comme décrit plus haut ? 

Il y a un autre problème, mais dans le script Python : les doléances sont mal découpées, à la fin du tableau il y a le texte de plusieurs doléances il me semble.

**Comment by Atala** [comment]
Tu as un exemple pour que je double-check sur le wiki ? Il y a aussi des gens qui ont entré des doléances très longues qui recoupent plusieurs points et qui n'ont pas été découpées dans le wiki, je ne sais pas ce qu'ils veulent en faire.

**Comment by alexsegura** [comment]
Tu peux faire un prettry print du JSON dans le Gist ? C'est plus facile de s'en rendre compte.

**Comment by Atala** [comment]
[result.txt](https://github.com/nuitdebout/wordpress/files/263297/result.txt)

**Comment by alexsegura** [comment]
Tu peux le mettre dans le Gist stp ?

https://gist.github.com/Atala/e4f5ceb6d71dacaf21a71b6ebf023486

**Comment by Atala** [comment]
Fait. (excuse je croyais que ça allait être trop chiant à c/c, car trop long)

**Comment by alexsegura** [comment]
Doléances importées depuis le Wiki.
