### ISSUE TITLE
L'agenda est lent

### ISSUE THREAD

**Issue by colasbd** [nuitdebout/wordpress#143]
Très joli l'agenda mais il n'est pas réactif : quand on change de date, chez moi le chargement des données prend genre 2 secondes.

**Comment by alexsegura** [comment]
Oui c'est un première version, il faut qu'on mette du cache.

**Comment by alexsegura** [comment]
Ajout de cache dans f169ac46cdd9b5990323e6285511ba85fa4cbeca

**Comment by colasbd** [comment]
Cool. Je constate le changement.
