### ISSUE TITLE
Internationalize the website

### ISSUE THREAD

**Issue by mdamien** [nuitdebout/wordpress#148]
As said [here](http://questions.nuitdebout.fr/index.php?qa=4326&qa_1=nest-possible-que-contenu-site-soit-disponible-moins-anglais), It would be nice to have at least english so more people can join/understand the movement. Of course we can't translate everything but at least the homepage would be nice.

**Comment by alexsegura** [comment]
Pas pour le moment. 

De toutes façons, pour le moment on est sur nuitdebout.**fr**, donc ça n'a pas de sens que ce site soit multi-langues. 
On a le site nuitdebout.fr/globaldebout qui lui est multi-langue et dédié à l'international.

**Comment by mdamien** [comment]
pas vraiment d'accord but let this slide.

D'ailleurs le wiki est international est beaucoup plus facile a contribuer dessus, peut etre que ca devrait etre notre page d'acceuil

**Comment by ShNGD** [comment]
Bonsoir à vous, j'espère que vous allez bien, est-il, alors, possible de créer un second site multi-langage questions.nuitdebout.com ou questions.nuitglobadebout.com vue l'ampleur que prend le mouvement Nuit Global Debout hors de l'espace francophone?
Merci de votre attention, bon courage et portez-vous bien!
