### ISSUE TITLE
Refonte de la nav

### ISSUE THREAD

**Issue by uneyouya** [nuitdebout/wordpress#156]
![1 1_nuitdebout_nav](https://cloud.githubusercontent.com/assets/19183873/15360119/a52bc274-1d0c-11e6-9ca3-7a65a9eb0c08.jpg)
![1 2_nuitdebout_nav](https://cloud.githubusercontent.com/assets/19183873/15360120/a531af72-1d0c-11e6-91fd-65fcc77d25f0.jpg)
![1 3_nuitdebout_nav](https://cloud.githubusercontent.com/assets/19183873/15360121/a53ad1a6-1d0c-11e6-9d14-35db46d13fef.jpg)

**Comment by uneyouya** [comment]
@mex Menu mobile : 
![image](https://cloud.githubusercontent.com/assets/19183873/15362124/6b3d5f16-1d14-11e6-8a24-895222f147c0.png)

À voir si on affiche toutes les catégories d'emblée ou si on utilise un système pour expand les grandes catégories? Perso, je suis pour tout afficher.

**Comment by Atala** [comment]
@Nhacsam you're on it?

**Comment by uneyouya** [comment]
![1 1_nuitdebout_home](https://cloud.githubusercontent.com/assets/19183873/15604244/9cde8292-23ff-11e6-8ffa-4611a27f0ce9.jpg)
@mex, c'est celle-ci sorry!
