### ISSUE TITLE
Bandeau avec les actions en cours

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#159]
Le but est d'avoir un bandeau en haut du site, avec les évènements importants mis en avant (bandeau turquoise ci-dessous). 

![a52bc274-1d0c-11e6-9ca3-7a65a9eb0c08](https://cloud.githubusercontent.com/assets/1162230/15449681/0d3d795a-1f85-11e6-9ba1-01f748332089.jpg)

Dans un premier temps, les données seront tirées de OpenAgenda. 
On peut par la suite imaginer plusieurs sources de données (articles, fil Telegram...), mais OpenAgenda est bien maîtrisé et utilisé. 

OpenAgenda dispose d'une fonctionnalité "Mettre en une" : on va donc simplement récupérer les évènements de la journée qui sont en une. 

<img width="830" alt="capture d ecran 2016-05-21 a 18 53 19" src="https://cloud.githubusercontent.com/assets/1162230/15449690/67150a74-1f85-11e6-9507-c5ca3be45157.png">

---
- Voir comment récupérer les évènements en une, et ajouter une fonction `get_featured_events($date)` dans `lib/openagenda.php`
- Mettre en place le bandeau et le JavaScript pour faire tourner les évènements dans le bandeau. 
- Le bandeau contient simplement un lien vers l'évènement.

**Comment by ghost** [comment]
Taranis a un bandeau plutôt bien fait

http://www.taranisnews.com

**Comment by fadomire** [comment]
i close, it seems implemented, see #161
