### ISSUE TITLE
Texe illisible

### ISSUE THREAD

**Issue by ghost** [nuitdebout/wordpress#163]
![fireshot screen capture 089 - nuitdebout chaque jour nous sommes des milliers a occuper l espace public pour reprendre notre pl_ - nuitdebout_fr](https://cloud.githubusercontent.com/assets/11270285/15802037/1979792e-2a9f-11e6-9ff0-25d6eb9279c5.jpg)

Les textes des 2 info importantes en page d'accueil sont difficilement lisibles.

**Comment by uneyouya** [comment]
Ajouter :
background: rgba (0,0,0,0.3);   => masque sur l'image
text-shadow: 0px 2px 4px rgba(0,0,0,0.50);

<3

**Comment by Nhacsam** [comment]
Done : #194
