### ISSUE TITLE
Augmenter la taille max d'upload

### ISSUE THREAD

**Issue by ghost** [nuitdebout/wordpress#184]
Une personne a besoin d'uploader un fichier dépassant 1 Mo

**Comment by alexsegura** [comment]
Fixé. 

Il faut : 
- augmenter les valeurs de `upload_max_filesize` et `post_max_size` dans `php.ini`
- augmenter la taille autorisée dans l'admin du réseau Wordpress
- augmenter la valeur de `client_max_body_size` dans la conf Nginx

Pas simple 😄
