### ISSUE TITLE
Affichage de la 10e card bug

### ISSUE THREAD

**Issue by ghost** [nuitdebout/wordpress#185]
![fireshot screen capture 083 - nuitdebout chaque jour nous sommes des milliers a occuper l espace public pour reprendre notre pl_ - nuitdebout_fr_dxo](https://cloud.githubusercontent.com/assets/11270285/15726032/9bd4cd16-2846-11e6-91de-18793b30f496.jpg)

**Comment by Atala** [comment]
Fixed here a1d8738bd29b42a0860066c6437cb418c92e2309
