### ISSUE TITLE
un wpmu actif

### ISSUE THREAD

**Issue by xavierle** [nuitdebout/wordpress#2]
bonjour

pour info il y a deja un wpmu actif avec quelques collectifs qui sont presents dessus

https://nuitdebout.cc/

peut etre trouver un moyen de faire suivre les deux ensemble

ca en parle ici

https://forum.nuitdebout.cc

**Comment by tomplays** [comment]
oui depuis deux jours j essaye de vous trouver, vous avez un git ?

**Comment by xavierle** [comment]
actuellement pas. mais si besoin ca peut se faire.

si cela te tente d etre admin dessus pas de pb
actuellement je monte les plugins en fonctions des besoins exprimés par villes.

j ai un compte pro wpmudev donc access a de nombreux plugins wOrdpress pro.

**Comment by tomplays** [comment]
oui que je vois ce que vous avez !

**Comment by xavierle** [comment]
enregistre toi et dis moi quel est ton pseudo

**Comment by tomplays** [comment]
https://forum.nuitdebout.cc/users/tom_plays/activity

**Comment by xavierle** [comment]
tu peux creer un compte la
https://nuitdebout.cc/wp-login.php?action=register

**Comment by alexsegura** [comment]
Je ferme pour faire le ménage 😉
