### ISSUE TITLE
Site live

### ISSUE THREAD

**Issue by guilhem** [nuitdebout/wordpress#34]
Bonjour,

Comme dit hier en commission, nous avons finis d'intégrer le site sur notre plateforme themecloud.
Un site est déjà "live" http://nuitdebout.themecloud.me/ et pour montrer un processus possible, nous avons créé un template pour que tout le monde puisse avoir son propre site en 1 clic : https://www.themecloud.io/theme/Themecloudio/Nuit-Debout-Alpha

Tout ceci est bien sûr "alpha" pour le moment et servent à titre d'exemple. Elles ne sont pas indexées pour le moment.

Notre processus n'inclus pas de gratuité par template pour le moment, mais nous nous efforceront de passer tous les sites "nuitdebout" en gratuit et illimité avant la fin des 15 jours d'essai (sans restriction).

Camaradement votre,
Guilhem

**Comment by tomplays** [comment]
peut etre un coucou sur le chat' aurait été bien..

**Comment by tomplays** [comment]
Juste pour reprendre : tu proposes d'héberger ce template sur un site commercial dont tu es sembles-t-il le represéntant. En changeant les copyright d'ailleurs et la licence.. "nous avons finis d'intégrer le site" cad copier-coller le dossier dans le dossier des themes.. à zéro commit sur le code. comment te dire..

**Comment by alexsegura** [comment]
Hello @guilhem, tu proposes d'héberger gratuitement des sites Wordpress ?

**Comment by guilhem** [comment]
Bonjour à tous,
Alors premièrement je pense que ce serait bon de calmer les mots et les propos.
Nous sommes tous ici pour faire de notre mieux et dans un but commun.

Pour revenir sur les points :
- Avant même de faire ce travail, j'en ai parlé en commission avec un retour plutôt positif à mon sens. Le chat est, pour moi, tel quel, un foutoir permanent. Je trouvais plus judicieux de venir en discuter directement sur GH avec les développeurs (comme j'en ai l'habitude sur les différents projets auxquel je participe).
- Comme dit précédemment (et indiqué dans le titre du thème), tout ceci est encore "alpha" et sujet à discussion avec tous
- Oui je propose d’héberger ce template sur la plateforme pour laquelle je travaille. C'est bien entendu une entreprise, mais nous proposons gratuitement l’hébergement pour nuitdebout... tout comme github le fait en ce moment pour le code.
- 0 commit dans le code... alors que 2 de mes PR #32 et #33 viennent d'être mergés je trouve cela assez fort :)
- La licence est GPL n'interdit absolument pas la mise à disposition (meme à titre onéreux) du moment que les sources sont mises à disposition (ce que l'on fait via un access FTP complet) ou une demande par mail. ( _think of “free” as in “free speech,” not as in “free beer”._)

Je pense que le procès en intention est assez mal placé pour quelqu'un comme moi.
@tomplays je t'invite à regarder mes contributions au monde de libre.

@alexsegura notre plateforme permet de créer des sites wordpress à partir d'un "template". Je pense que ce système "décentralisé" est plutôt pas mal pour nuitdebout.
Toutes les différentes villes pourraient avoir le leur et le gérer totalement à leur façon (aussi bien au niveau de la ligne éditoriale que de l’administration "pure").

Et pour finir de vous convaincre (j'éspère), notre plateforme est uniquement constituée de composants opensource : CoreOS, etcd, docker, nginx, haproxy, Mariadb Cluster + [des composants "home made"](https://github.com/themecloud)

**Comment by alexsegura** [comment]
Bras en forme de tente, "on se détend" 😃 

C'est super cool de proposer ça, big up. 

Effectivement, il y a certainement un besoin en sites Wordpress pour toutes les sous-composantes de Nuit Debout (par exemple, BiblioDebout, ArtistesDebout), il faudrait recenser tous ceux qui ont ce besoin afin de leur fournir de l'infrastructure. 

D'autres initiatives de ce type ont vu le jour, est-ce que tu connais [nuitdebout.cc](https://nuitdebout.cc/a-propos/) ?

Je pense qu'il y a également une réflexion à mener sur "l'utilité" de chaque bout d'infrastructure que chacun peut apporter, et distinguer les objectifs de chaque plateforme (site portail "officiel", site de ville, site de commission, plateforme dédiée, etc...)

Le mieux c'est qu'on boive un jus de carotte ensemble, non ? 😄

**Comment by tomplays** [comment]
suis désolé, j'étais fatigué.

**Comment by guilhem** [comment]
C'est sûr que cela peut ouvrir plein de possibilités... et donc de questions :)

@tomplays pas de soucis t’inquiète, je sais que nous essayons tous de faire au mieux ^^
Que l'on reste tous humain est plutôt bon signe.

@alexsegura j'ai juste vu l'initiative sur #2 mais tant qu'ils n'ont pas de git nous ne pouvons proposer un hebergement du theme.

Je pense en effet que le jus de carotte (houblonné pour moi) est important. Je devrais être dimanche sur la place pour la commission.
On peut se retrouver un peu avant et se sera de toute façon un sujet de discussion pendant la commission / ateliers. :)

**Comment by alexsegura** [comment]
Je t'ai envoyé un mail 😉

**Comment by alexsegura** [comment]
Je ferme pour faire de la place pour le Kanban 😉

**Comment by guilhem** [comment]
pas de soucis @alexsegura ;)

**Comment by alexsegura** [comment]
Pour info on va essayer un nouveau mode de fonctionnement : utiliser les issues Github couplé à ZenHub 
- pour se répartir les tâches plus efficacement
- plus de visibilité sur qui fait quoi
- une seule interface
- et plein d'autres avantages en théorie 😄 

Plus d'infos à suivre dans le README, je vais le mettre à jour.

**Comment by guilhem** [comment]
Ah génial.
J'ai l'habitude d'utiliser waffle.io, mais je vais regarder zenhub ;)
