### ISSUE TITLE
Le widget "Réseaux" ne permet pas de ne remplir que certains liens

### ISSUE THREAD

**Issue by louisbl** [nuitdebout/wordpress#44]
Si on ne remplit pas tous les liens, il n'y a que les premiers qui apparaissent. Par exemple on ne peut pas remplir uniquement `Facebook`, `Twitter` et ensuite `Chat`, `Chat` n'apparaitra pas.

**Comment by tomplays** [comment]
"chat" et "wiki" sont 2 exceptions (pour le moment) donc meme si tu le remplis l'icone n'y sera pas. (à statuer pour correction)
