### ISSUE TITLE
Plugin de statistique

### ISSUE THREAD

**Issue by louisbl** [nuitdebout/wordpress#45]
Même nuit debout aime les chiffres :)
Pour donner accès à chaque ville à des statistiques sur son site, [WP Statistics](http://wordpress.org/plugins/wp-statistics/) est un plugin qui fonctionne sans aucune dépendance extérieur.

**Comment by alexsegura** [comment]
Bonne idée 👍

**Comment by tomplays** [comment]
Piwik est activable sur les sous-sites, à définir pour en ajouter d'autres
