### ISSUE TITLE
Permettre de répondre aux demandes de contact directement depuis le back-office

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#91]
Actuellement, les formulaires de contact sont créés via le plugin "Contact Form 7", et les contacts sont stockés dans le back-office via le plugin "Flamingo". 

Cependant, ce plugin ne permet pas de répondre directement depuis le back-office. 
Il faudrait trouver un moyen de répondre simplement depuis le back-office.

**Comment by tomplays** [comment]
plugin modifié "maison" pour pouvoir le faire (sources non dispo pour le moment sur git)

**Comment by alexsegura** [comment]
On va utiliser un mail partagé ou alors [ZenDesk Inbox](https://www.zendesk.com/inbox/)
