### ISSUE TITLE
Refonte de la home

### ISSUE THREAD

**Issue by alexsegura** [nuitdebout/wordpress#99]
Voici le mockup proposé par @uneyouya pour la refonte de la home

À discuter

![1_ux_hp_nuitdebout20160503](https://cloud.githubusercontent.com/assets/1162230/15008757/c9515cb6-11e2-11e6-9830-6c45dd775d28.jpg)

**Comment by uneyouya** [comment]
Bon donc ça a été discuté cette histoire finalement? :) on se fait ça tous ensemble sérieusement quand je rentre.

**Comment by uneyouya** [comment]
![1 1_nuitdebout_home](https://cloud.githubusercontent.com/assets/19183873/15575215/f560fdea-2351-11e6-82d6-44f1feb5bab8.jpg)
